"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.CALABASH_SPECIALUI_LEVEL = exports.VISION_REFINE_FILTER_QUALITY = exports.VISION_RECOVERT_FILTER_DEPERCATE = exports.VISION_RECOVERT_FILTER_UNDEPERCATE = exports.VISION_RECOVERY_SORT_GROUP_ID = exports.VISION_RECOVERY_SLOT_MAX_NUM = undefined;
exports.VISION_RECOVERY_SLOT_MAX_NUM = 5;
exports.VISION_RECOVERY_SORT_GROUP_ID = 31;
exports.VISION_RECOVERT_FILTER_UNDEPERCATE = 0;
exports.VISION_RECOVERT_FILTER_DEPERCATE = 1;
exports.VISION_REFINE_FILTER_QUALITY = 5;
exports.CALABASH_SPECIALUI_LEVEL = 26; //# sourceMappingURL=CalabashDefine.js.map