"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.UiTabViewManager = undefined;
const AdvanceNoticeNewActivityTabView_1 = require("../Module/Activity/ActivityContent/AdvanceNotice/AdvanceNoticeNewActivityTabView");
const AdvanceNoticeNewAreaTabView_1 = require("../Module/Activity/ActivityContent/AdvanceNotice/AdvanceNoticeNewAreaTabView");
const AdvanceNoticeNewEnemyTabView_1 = require("../Module/Activity/ActivityContent/AdvanceNotice/AdvanceNoticeNewEnemyTabView");
const AdvanceNoticeNewJourneyTabView_1 = require("../Module/Activity/ActivityContent/AdvanceNotice/AdvanceNoticeNewJourneyTabView");
const AdvanceNoticeNewRoleTabView_1 = require("../Module/Activity/ActivityContent/AdvanceNotice/AdvanceNoticeNewRoleTabView");
const AdvanceNoticeNewSkinTabView_1 = require("../Module/Activity/ActivityContent/AdvanceNotice/AdvanceNoticeNewSkinTabView");
const AdvanceNoticeNewSystemOptimizeTabView_1 = require("../Module/Activity/ActivityContent/AdvanceNotice/AdvanceNoticeNewSystemOptimizeTabView");
const BossRushBuffSelectView_1 = require("../Module/Activity/ActivityContent/BossRush/BossRushBuffSelectView");
const BossRushLevelDetailView_1 = require("../Module/Activity/ActivityContent/BossRush/BossRushLevelDetailView");
const BossRushRewardView_1 = require("../Module/Activity/ActivityContent/BossRush/BossRushRewardView");
const BossRushSelectView_1 = require("../Module/Activity/ActivityContent/BossRush/BossRushSelectView");
const FishingTimeLimitRewardTabView_1 = require("../Module/Activity/ActivityContent/Fishing/Activity/View/FishingTimeLimitRewardTabView");
const FishingTimeLimitShopTabView_1 = require("../Module/Activity/ActivityContent/Fishing/Activity/View/FishingTimeLimitShopTabView");
const DockyardBuyTabView_1 = require("../Module/Activity/ActivityContent/Fishing/Dockyard/Shop/DockyardBuyTabView");
const DockyardSellTabView_1 = require("../Module/Activity/ActivityContent/Fishing/Dockyard/Shop/DockyardSellTabView");
const FishingNormalTechView_1 = require("../Module/Activity/ActivityContent/Fishing/FishingTech/FishingNormalTechView");
const FishingRoleTechView_1 = require("../Module/Activity/ActivityContent/Fishing/FishingTech/FishingRoleTechView");
const RewardShopTabView_1 = require("../Module/Activity/ActivityContent/MoonChasing/Main/Reward/Shop/RewardShopTabView");
const RewardTargetTabView_1 = require("../Module/Activity/ActivityContent/MoonChasing/Main/Reward/Target/RewardTargetTabView");
const RegressBpRewardTabView_1 = require("../Module/Activity/ActivityContent/Regress/BPView/RegressBpRewardTabView");
const RegressBpTaskTabView_1 = require("../Module/Activity/ActivityContent/Regress/BPView/RegressBpTaskTabView");
const AdventureTargetView_1 = require("../Module/AdventureGuide/Views/AdventureTargetView");
const MonsterDetectView_1 = require("../Module/AdventureGuide/Views/MonsterDetectView");
const NewSoundAreaView_1 = require("../Module/AdventureGuide/Views/NewSoundAreaView");
const PeriodicityChallengeView_1 = require("../Module/AdventureGuide/Views/PeriodicityChallengeView");
const CalabashCollectTabView_1 = require("../Module/Calabash/New/CalabashCollect/CalabashCollectTabView");
const CalabashLevelUpTabView_1 = require("../Module/Calabash/New/CalabashLevelUp/CalabashLevelUpTabView");
const PhantomBattleFettersTabView_1 = require("../Module/Calabash/New/PhantomBattleFetters/PhantomBattleFettersTabView");
const VisionRecoveryTabView_1 = require("../Module/Calabash/New/VisionRecovery/VisionRecoveryTabView");
const VisionRefineTabView_1 = require("../Module/Calabash/New/VisionRefine/VisionRefineTabView");
const DailyActivityView_1 = require("../Module/DailyActivity/View/DailyActivityView");
const RolePreviewDescribeTabView_1 = require("../Module/Gacha/PreviewView/RolePreviewDescribeTabView");
const RolePreviewResonanceTabView_1 = require("../Module/Gacha/PreviewView/RolePreviewResonanceTabView");
const RolePreviewSkillTabView_1 = require("../Module/Gacha/PreviewView/RolePreviewSkillTabView");
const HonamiStoryEquipTabView_1 = require("../Module/HonamiStory/View/HonamiStoryEquipTabView");
const MotorcycleLevelInfoTabView_1 = require("../Module/Motorcycle/Develop/View/MotorcycleLevelInfoTabView");
const MotorcycleTaskTabView_1 = require("../Module/Motorcycle/Develop/View/MotorcycleTaskTabView");
const MotorcycleTechTreeTabView_1 = require("../Module/Motorcycle/Develop/View/MotorcycleTechTreeTabView");
const MotorcycleDiyStickerTabView_1 = require("../Module/Motorcycle/DIY/View/TabView/MotorcycleDiyStickerTabView");
const MotorcycleDiyMainView_1 = require("../Module/Motorcycle/DIY/View/View/MotorcycleDiyMainView");
const BattlePassRewardView_1 = require("../Module/PayShop/BattlePass/BattlePassTabView/BattlePassRewardView");
const BattlePassTaskView_1 = require("../Module/PayShop/BattlePass/BattlePassTabView/BattlePassTaskView");
const BattlePassWeaponView_1 = require("../Module/PayShop/BattlePass/BattlePassTabView/BattlePassWeaponView");
const MonthCardView_1 = require("../Module/PayShop/MonthCard/MonthCardView");
const BabelTowerShopView_1 = require("../Module/PayShop/PayShopTab/BabelTowerShopView");
const DiscountShopView_1 = require("../Module/PayShop/PayShopTab/DiscountShopView");
const MotorSkinTabView_1 = require("../Module/PayShop/PayShopTab/MotorSkinTabView");
const PayPackageShopView_1 = require("../Module/PayShop/PayShopTab/PayPackageShopView");
const PayShopRechargeView_1 = require("../Module/PayShop/PayShopTab/PayShopRechargeView");
const PayShopRecommendView_1 = require("../Module/PayShop/PayShopTab/PayShopRecommendView");
const PayShopSkinView_1 = require("../Module/PayShop/PayShopTab/PayShopSkinView");
const RogueShopTabView_1 = require("../Module/PayShop/PayShopTab/RogueShopTabView");
const RoleSkinTabView_1 = require("../Module/PayShop/PayShopTab/RoleSkinTabView");
const ShopFlySkinTabView_1 = require("../Module/PayShop/PayShopTab/ShopFlySkinTabView");
const RogueIllustratedEventTabView_1 = require("../Module/PermanentRogue/View/RogueIllustratedEventTabView");
const RogueIllustratedTokenTabView_1 = require("../Module/PermanentRogue/View/RogueIllustratedTokenTabView");
const VisionIdentifyView_1 = require("../Module/Phantom/Vision/View/VisionIdentifyView");
const VisionLevelUpView_1 = require("../Module/Phantom/Vision/View/VisionLevelUpView");
const PhantomArenaCollectBadgeTabView_1 = require("../Module/PhantomArena/Prepare/Collect/PhantomArenaCollectBadgeTabView");
const PhantomArenaCollectCardTabView_1 = require("../Module/PhantomArena/Prepare/Collect/PhantomArenaCollectCardTabView");
const PhantomArenaEntranceShopTabView_1 = require("../Module/PhantomArena/Prepare/Entrance/PhantomArenaEntranceShopTabView");
const PhantomArenaEntranceTaskTabView_1 = require("../Module/PhantomArena/Prepare/Entrance/PhantomArenaEntranceTaskTabView");
const RogueBattleMapSummaryFetterTabView_1 = require("../Module/RogueBattle/View/RogueBattleMapSummaryFetterTabView");
const RogueBattleMapSummaryGridEffectTabView_1 = require("../Module/RogueBattle/View/RogueBattleMapSummaryGridEffectTabView");
const RogueBattleMapSummaryTeamTabView_1 = require("../Module/RogueBattle/View/RogueBattleMapSummaryTeamTabView");
const RogueBattleSummaryTeamTabView_1 = require("../Module/RogueBattle/View/RogueBattleSummaryTeamTabView");
const RogueBattleSummaryTokenTabView_1 = require("../Module/RogueBattle/View/RogueBattleSummaryTokenTabView");
const RoleHandBookPreviewView_1 = require("../Module/RoleHandBook/RoleHandBookPreviewView");
const RoleFavorTabView_1 = require("../Module/RoleUi/RoleFavor/RoleFavorTabView");
const ResonanceChainView_1 = require("../Module/RoleUi/RoleResonance/ResonanceChainView");
const RoleSkillTreeView_1 = require("../Module/RoleUi/RoleSkill/RoleSkillTreeView");
const RoleAttributeTabView_1 = require("../Module/RoleUi/TabView/RoleAttributeTabView");
const RolePreviewAttributeTabView_1 = require("../Module/RoleUi/TabView/RolePreviewAttributeTabView");
const RoleVisionTabView_1 = require("../Module/RoleUi/TabView/RoleVisionTabView");
const RoleWeaponTabView_1 = require("../Module/RoleUi/TabView/RoleWeaponTabView");
const RoleSkinTabView_2 = require("../Module/Skin/Role/View/RoleSkinTabView");
const CalabashSkinTabView_1 = require("../Module/Skin/Tab/Calabash/CalabashSkinTabView");
const FlySkinTabView_1 = require("../Module/Skin/Tab/Fly/FlySkinTabView");
const RoleSkinRecommendView_1 = require("../Module/Skin/Tab/Role/RoleSkinRecommendView");
const WeaponSkinTabView_1 = require("../Module/Skin/Tab/Weapon/WeaponSkinTabView");
const SurvivorsItemTabView_1 = require("../Module/SurvivorsRogue/External/TabView/SurvivorsItemTabView");
const SurvivorsRoleTabView_1 = require("../Module/SurvivorsRogue/External/TabView/SurvivorsRoleTabView");
const SurvivorsWeaponTabView_1 = require("../Module/SurvivorsRogue/External/TabView/SurvivorsWeaponTabView");
const WeaponBreachView_1 = require("../Module/Weapon/Breach/WeaponBreachView");
const WeaponLevelUpView_1 = require("../Module/Weapon/LevelUp/WeaponLevelUpView");
const WeaponResonanceView_1 = require("../Module/Weapon/Reasonance/WeaponResonanceView");
const UiTabViewStorage_1 = require("../Ui/UiTabViewStorage");
class UiTabViewManager {
  static Init() {
    UiTabViewStorage_1.UiTabViewStorage.AddUiTabViewBase([["RoleAttributeTabView", RoleAttributeTabView_1.RoleAttributeTabView, "UiTabView_RoleAttribute_Prefab"], ["RoleSkillTabView", RoleSkillTreeView_1.RoleSkillTreeView, "UiTabView_RoleSkillTree_Prefab"], ["RoleWeaponTabView", RoleWeaponTabView_1.RoleWeaponTabView, "UiTabView_RoleWeapon_Prefab"], ["RoleFavorTabView", RoleFavorTabView_1.RoleFavorTabView, "UiView_Tab_RoleDangan_Prefab"], ["RolePreviewAttributeTabView", RolePreviewAttributeTabView_1.RolePreviewAttributeTabView, "UiTabView_RoleAttributePreview_Prefab"], ["WeaponLevelUpView", WeaponLevelUpView_1.WeaponLevelUpView, "UiTabView_WeaponLevelUp_Prefab"], ["WeaponBreachView", WeaponBreachView_1.WeaponBreachView, "UiTabView_WeaponBreach_Prefab"], ["WeaponResonanceView", WeaponResonanceView_1.WeaponResonanceView, "UiTabView_WeaponResonance_Prefab"], ["RolePhantomTabView", RoleVisionTabView_1.RoleVisionTabView, "UiItem_VisionIMain_New"], ["PayShopGiftBagView", DiscountShopView_1.DiscountShopView, "UiItem_Exchange1"], ["RogueShopTabView", RogueShopTabView_1.RogueShopTabView, "UiItem_Exchange1"], ["BabelTowerShopTabView", BabelTowerShopView_1.BabelTowerShopTabView, "UiItem_Exchange1"], ["PayItemTabView", PayShopRechargeView_1.PayShopRechargeView, "UiItem_Exchange1"], ["PayShopRecommendView", PayShopRecommendView_1.PayShopRecommendView, "UiItem_Exchange1"], ["PayShopExchangeEntryView", DiscountShopView_1.DiscountShopView, "UiItem_Exchange1"], ["PayPackageShopView", PayPackageShopView_1.PayPackageShopView, "UiItem_Exchange1"], ["PayShopSkinView", PayShopSkinView_1.PayShopSkinView, "UiItem_Exchange1"], ["RoleShopSkinTabView", RoleSkinTabView_1.RoleShopSkinTabView, "UiItem_ShopSkinList"], ["ShopFlySkinTabView", ShopFlySkinTabView_1.ShopFlySkinTabView, "UiItem_ShopSkinList"], ["RolePreviewDescribeTabView", RolePreviewDescribeTabView_1.RolePreviewDescribeTabView, "UiTabView_RoleDescribe_Prefab"], ["RolePreviewSkillTabView", RolePreviewSkillTabView_1.RolePreviewSkillTabView, "UiTabView_RoleSkill_Prefab"], ["RolePreviewResonanceTabView", RolePreviewResonanceTabView_1.RolePreviewResonanceTabView, "UiTabView_RoleResonance_Prefab"], ["MonthCardView", MonthCardView_1.MonthCardView, "UiItem_MonthlyCard_Prefab"], ["RoleSkinRecommendView", RoleSkinRecommendView_1.RoleSkinRecommendView, "UiItem_ShopSkin"], ["RoleResonanceTabNewView", ResonanceChainView_1.ResonanceChainView, "UiTabView_RoleResonance_New_Prefab"], ["RoleHandBookPreviewView", RoleHandBookPreviewView_1.RoleHandBookPreviewView, "UiTabView_RoleDescribe_Prefab"], ["AdventureTargetView", AdventureTargetView_1.AdventureTargetView, "UiView_Completion"], ["MonsterDetectView", MonsterDetectView_1.MonsterDetectView, "UiView_Survey"], ["DisposableChallengeView", NewSoundAreaView_1.NewSoundAreaView, "UiView_NewSoundArea"], ["NewSoundAreaView", NewSoundAreaView_1.NewSoundAreaView, "UiView_NewSoundArea"], ["DailyActivityTabView", DailyActivityView_1.DailyActivityView, "UiItem_Active"], ["PeriodicityChallengeView", PeriodicityChallengeView_1.PeriodicityChallengeView, "UiItem_DevelopmentPeriodPage"], ["VisionLevelUpView", VisionLevelUpView_1.VisionLevelUpView, "UiView_VisionLevelUp"], ["VisionIdentifyView", VisionIdentifyView_1.VisionIdentifyView, "UiView_VisionIdentify"], ["CalabashLevelUpTabView", CalabashLevelUpTabView_1.CalabashLevelUpTabView, "UiItem_VisionUpgrade"], ["CalabashCollectTabView", CalabashCollectTabView_1.CalabashCollectTabView, "UiItem_VisionlMap"], ["PhantomBattleFettersTabView", PhantomBattleFettersTabView_1.PhantomBattleFettersTabView, "UiItem_VisionFetter"], ["VisionRecoveryTabView", VisionRecoveryTabView_1.VisionRecoveryTabView, "UiView_VisionRecovery"], ["VisionRefineTabView", VisionRefineTabView_1.VisionRefineTabView, "UiView_VisionRefining"], ["WeaponSkinTabView", WeaponSkinTabView_1.WeaponSkinTabView, "UiItem_RoleWeaponSkin"], ["RoleSkinTabView", RoleSkinTabView_2.RoleSkinTabView, "UiItem_RoleSkin"], ["FlySkinTabView", FlySkinTabView_1.FlySkinTabView, "UiItem_FlySkin"], ["CalabashSkinTabView", CalabashSkinTabView_1.CalabashSkinTabView, "UiItem_RoleDataDockSkin"], ["BattlePassRewardView", BattlePassRewardView_1.BattlePassRewardView, "UiItem_BattlePassReward"], ["BattlePassTaskView", BattlePassTaskView_1.BattlePassTaskView, "UiItem_BattlePassMission"], ["BattlePassWeaponView", BattlePassWeaponView_1.BattlePassWeaponView, "UiItem_WeaponPreview"], ["BossRushBuffSelectView", BossRushBuffSelectView_1.BossRushBuffSelectView, "UiItem_BossRushEntryCard"], ["BossRushLevelDetailView", BossRushLevelDetailView_1.BossRushLevelDetailView, "UiItem_BossrushLevelInfo"], ["BossRushSelectView", BossRushSelectView_1.BossRushSelectView, "UiItem_BossrushSleLevel"], ["BossRushRewardView", BossRushRewardView_1.BossRushRewardView, "UiItem_BossrushReward"], ["RewardTargetTabView", RewardTargetTabView_1.RewardTargetTabView, "UiItem_ShopMission"], ["RewardShopTabView", RewardShopTabView_1.RewardShopTabView, "MoonChasing_UiItem_ShopItem"], ["DockyardSellTabView", DockyardSellTabView_1.DockyardSellTabView, "UiItem_ShopSell"], ["DockyardBuyTabView", DockyardBuyTabView_1.DockyardBuyTabView, "UiItem_ShopList"], ["FishingNormalTechView", FishingNormalTechView_1.FishingNormalTechView, "UiItem_NavigationUpgradeSkill"], ["FishingRoleTechView", FishingRoleTechView_1.FishingRoleTechView, "UiItem_RoleUpgrade"], ["FishingTimeLimitRewardTabView", FishingTimeLimitRewardTabView_1.FishingTimeLimitRewardTabView, "UiItem_LimitTimeReward"], ["FishingTimeLimitShopTabView", FishingTimeLimitShopTabView_1.FishingTimeLimitShopTabView, "UiItem_LimitTimeShop"], ["RogueIllustratedTokenTabView", RogueIllustratedTokenTabView_1.RogueIllustratedTokenTabView, "UiItem_IllustratedTokenItem"], ["RogueIllustratedEventTabView", RogueIllustratedEventTabView_1.RogueIllustratedEventTabView, "UiItem_RogueHandbook"], ["RogueBattleMapSummaryTeamTabView", RogueBattleMapSummaryTeamTabView_1.RogueBattleMapSummaryTeamTabView, "UiItem_RogueTeamView"], ["RogueBattleMapSummaryFettersTabView", RogueBattleMapSummaryFetterTabView_1.RogueBattleMapSummaryFettersTabView, "UiItem_RogueFettersBuff"], ["RogueBattleSummaryTeamTabView", RogueBattleSummaryTeamTabView_1.RogueBattleSummaryTeamTabView, "UiItem_RogueRoleInfo"], ["RogueBattleMapSummaryGridEffectTabView", RogueBattleMapSummaryGridEffectTabView_1.RogueBattleMapSummaryGridEffectTabView, "UiItem_BattleAddtionView"], ["RogueBattleSummaryTokenTabView", RogueBattleSummaryTokenTabView_1.RogueBattleSummaryTokenTabView, "UiItem_RogueTokenInfo"], ["SurvivorsRoleTabView", SurvivorsRoleTabView_1.SurvivorsRoleTabView, "UiView_SurvivorsHandbookRole"], ["SurvivorsItemTabView", SurvivorsItemTabView_1.SurvivorsItemTabView, "UiView_SurvivorsHandbookItem"], ["SurvivorsWeaponTabView", SurvivorsWeaponTabView_1.SurvivorsWeaponTabView, "UiView_SurvivorsHandbookWeapon"], ["PhantomArenaCollectCardTabView", PhantomArenaCollectCardTabView_1.PhantomArenaCollectCardTabView, "UiItem_SoundRemnantArenaCollectCard"], ["PhantomArenaCollectCardTabViewNew", PhantomArenaCollectCardTabView_1.PhantomArenaCollectCardTabView, "UiItem_SoundRemnantArenaCollectCardNew"], ["PhantomArenaCollectBadgeTabView", PhantomArenaCollectBadgeTabView_1.PhantomArenaCollectBadgeTabView, "UiItem_SoundRemnantArenaCollectBadge"], ["PhantomArenaEntranceTaskTabView", PhantomArenaEntranceTaskTabView_1.PhantomArenaEntranceTaskTabView, "UiItem_SoundRemnantArenaMission"], ["PhantomArenaEntranceShopTabView", PhantomArenaEntranceShopTabView_1.PhantomArenaEntranceShopTabView, "UiItem_SoundRemnantArenaShop"], ["HonamiStoryEquipTabView", HonamiStoryEquipTabView_1.HonamiStoryEquipTabView, "UiItem_HonamiStoryBackpack"], ["AdvanceNoticeNewRoleTabView", AdvanceNoticeNewRoleTabView_1.AdvanceNoticeNewRoleTabView, "UiItem_RolePreview"], ["AdvanceNoticeNewJourneyTabView", AdvanceNoticeNewJourneyTabView_1.AdvanceNoticeNewJourneyTabView, "UiItem_JourneyPreview"], ["AdvanceNoticeNewAreaTabView", AdvanceNoticeNewAreaTabView_1.AdvanceNoticeNewAreaTabView, "UiItem_MapPreview"], ["AdvanceNoticeNewSkinTabView", AdvanceNoticeNewSkinTabView_1.AdvanceNoticeNewSkinTabView, "UiItem_BusinessPreview"], ["AdvanceNoticeNewEnemyTabView", AdvanceNoticeNewEnemyTabView_1.AdvanceNoticeNewEnemyTabView, "UiItem_MonsterPreview"], ["AdvanceNoticeNewActivityTabView", AdvanceNoticeNewActivityTabView_1.AdvanceNoticeNewActivityTabView, "UiItem_ActivityPreview"], ["AdvanceNoticeNewSystemOptimizeTabView", AdvanceNoticeNewSystemOptimizeTabView_1.AdvanceNoticeNewSystemOptimizeTabView, "UiItem_OptimizePreview"], ["MotorcycleLevelInfoTabView", MotorcycleLevelInfoTabView_1.MotorcycleLevelInfoTabView, "UiView_MotorcycleDevelopment"], ["MotorcycleTechTreeTabView", MotorcycleTechTreeTabView_1.MotorcycleTechTreeTabView, "UiView_MotorcycleTechTree"], ["MotorcycleTaskTabView", MotorcycleTaskTabView_1.MotorcycleTaskTabView, "UiView_MotorcycleTask"], ["MotorcycleDiyMainView", MotorcycleDiyMainView_1.MotorcycleDiyMainView, "UiView_MotorcycleDiy"], ["MotorcycleDiyStickerTabView", MotorcycleDiyStickerTabView_1.MotorcycleDiyStickerTabView, "UiView_MotorcycleDiySticker"], ["MotorSkinTabView", MotorSkinTabView_1.MotorSkinTabView, "UiItem_ShopMotoList"], ["RegressBpTaskTabView", RegressBpTaskTabView_1.RegressBpTaskTabView, "UiItem_CircumfluenceMissionList"], ["RegressBpRewardTabView", RegressBpRewardTabView_1.RegressBpRewardTabView, "UiItem_CircumfluenceCertificate"]]);
  }
}
exports.UiTabViewManager = UiTabViewManager;
//# sourceMappingURL=UiTabViewManager.js.map