"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.CHARACTER_NORMAL_NOT_RENDER_TICK_REDUCTION_INTERVAL_SIZE = exports.CHARACTER_NORMAL_NOT_RENDER_TICK_REDUCTION_START_SIZE = exports.CHARACTER_NORMAL_NOT_RENDER_MAX_INTERVAL = exports.CHARACTER_NORMAL_RENDER_TICK_REDUCTION_INTERVAL_SIZE = exports.CHARACTER_NORMAL_RENDER_TICK_REDUCTION_START_SIZE = exports.CHARACTER_NORMAL_RENDER_MAX_INTERVAL = undefined;
exports.CHARACTER_NORMAL_RENDER_MAX_INTERVAL = 60;
exports.CHARACTER_NORMAL_RENDER_TICK_REDUCTION_START_SIZE = 3000;
exports.CHARACTER_NORMAL_RENDER_TICK_REDUCTION_INTERVAL_SIZE = 300;
exports.CHARACTER_NORMAL_NOT_RENDER_MAX_INTERVAL = 120;
exports.CHARACTER_NORMAL_NOT_RENDER_TICK_REDUCTION_START_SIZE = 1000;
exports.CHARACTER_NORMAL_NOT_RENDER_TICK_REDUCTION_INTERVAL_SIZE = 100; //# sourceMappingURL=IPerformance.js.map