"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.DARK_COAST_HELP_ID = exports.PLOTPARAM_NUM = exports.RILINGCOLLECT_POOL_CONFIG_ID = exports.LAHAILUOSHENGXIA_POOL_CONFIG_ID = exports.PUPU_VILLAGE_QIQIU_POOL_CONFIG_ID = exports.PUPU_VILLAGE_POOL_CONFIG_ID = exports.DARK_COAST_POOL_CONFIG_ID = exports.CHENG_XIAO_SHAN_POOL_CONFIG_ID = exports.MING_SU_POOL_CONFIG_ID = exports.MING_SU_ITEM_CONFIG_ID = exports.EXP_BAR_ANIMATION_TIME = undefined;
exports.EXP_BAR_ANIMATION_TIME = 1200;
exports.MING_SU_ITEM_CONFIG_ID = 40040001;
exports.MING_SU_POOL_CONFIG_ID = 1;
exports.CHENG_XIAO_SHAN_POOL_CONFIG_ID = 2;
exports.DARK_COAST_POOL_CONFIG_ID = 3;
exports.PUPU_VILLAGE_POOL_CONFIG_ID = 4;
exports.PUPU_VILLAGE_QIQIU_POOL_CONFIG_ID = 5;
exports.LAHAILUOSHENGXIA_POOL_CONFIG_ID = 6;
exports.RILINGCOLLECT_POOL_CONFIG_ID = 7;
exports.PLOTPARAM_NUM = 3;
exports.DARK_COAST_HELP_ID = 113; //# sourceMappingURL=MingSuDefine.js.map