"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.LOCK_SPRITE_PATH = exports.DETAIL_SPRITE_PATH = exports.FILTER_SETTING_DEFAULT_FILTER_ID = exports.FILTER_SETTING_FILTER_TEXTURE_COUNT = exports.FILTER_SETTING_COORDINATE_TEXT_ID = exports.FILTER_SETTING_TITLE_ICON_RESOURCE_ID = exports.EYE_PROTECT_SETTING_HELP_ID = exports.FILTER_SETTING_TITLE_TEXT_ID = exports.FILTER_SETTING_HELP_ID = exports.TARGET_HIT_ITEM_FOR_RIGHT_ARROW = exports.TARGET_HIT_ITEM_FOR_LEFT_ARROW = exports.TARGET_HIT_ITEM_FOR_FILTER = exports.CUSTOM_TEXT_ID = exports.STOP_GUIDE_TAG = exports.mobileLoadingRangeScores = exports.pcLoadingRangeScores = exports.rayTracedShadowScores = exports.rayTracingReflectionScores = exports.rayTracingGIScores = exports.superResolutionScores = exports.vegetationDensityScores = exports.npcDensityScores = exports.bloomScores = exports.metalFxScores = exports.amdFsrScores = exports.motionBlurScores = exports.volumeLightScores = exports.volumeFogScores = exports.antiAliasingScores = exports.sceneAoScores = exports.imageDetailScores = exports.niagaraQualityScores = exports.shadowQualityScores = exports.mobileResolutionScores = exports.pcQualityLevelWeights = exports.pcQualityLevelScores = exports.qualityLevelScores = exports.SEETING_LOAD_OVER_COLOR = exports.SEETING_LOAD_LAGGY_COLOR = exports.SEETING_LOAD_FLUID_COLOR = exports.SEETING_LOAD_OVER = exports.SEETING_LOAD_LAGGY = exports.SEETING_LOAD_FLUID = exports.DEFAULT_FILTER_SENIOR_SETTING_VALUE = exports.DEFAULT_FILTER_SETTING_VALUE = exports.DEFAULT_FILTER_SETTING_INTENSITY_VALUE = exports.filterSettingParams = exports.makeImageQualityCustomSet = exports.noticeConfigSet = exports.cloudGameImageShowSettingsSet = undefined;
exports.disableSettingsWorldInstMap = exports.disableSettingsInstMap = exports.DETAIL_SPRITE_VISIBLE_COLOR_SRGB = undefined;
const GameSettingsDefine_1 = require("../../GameSettings/GameSettingsDefine");
exports.cloudGameImageShowSettingsSet = new Set([GameSettingsDefine_1.EFunction.MOTIONBLUR, GameSettingsDefine_1.EFunction.EnemyHitDisplayMode, GameSettingsDefine_1.EFunction.ShowDamage, GameSettingsDefine_1.EFunction.DynamicBones, GameSettingsDefine_1.EFunction.FlowAdaptation, GameSettingsDefine_1.EFunction.TeammateFx, GameSettingsDefine_1.EFunction.SkinDamageMode, GameSettingsDefine_1.EFunction.BasicGraphicSetting, GameSettingsDefine_1.EFunction.AutoExposure, GameSettingsDefine_1.EFunction.ImageDisplayMode, GameSettingsDefine_1.EFunction.Filter, GameSettingsDefine_1.EFunction.EyeProtection]);
exports.noticeConfigSet = new Set([GameSettingsDefine_1.EFunction.IMAGEQUALITY, GameSettingsDefine_1.EFunction.MOBILERESOLUTION, GameSettingsDefine_1.EFunction.RESOLUTION, GameSettingsDefine_1.EFunction.HIGHESTFPS, GameSettingsDefine_1.EFunction.SHADOWQUALITY, GameSettingsDefine_1.EFunction.NIAGARAQUALITY, GameSettingsDefine_1.EFunction.IMAGEDETAIL, GameSettingsDefine_1.EFunction.SCENEAO, GameSettingsDefine_1.EFunction.ANTIALISING, GameSettingsDefine_1.EFunction.VOLUMEFOG, GameSettingsDefine_1.EFunction.VOLUMELIGHT, GameSettingsDefine_1.EFunction.MOTIONBLUR, GameSettingsDefine_1.EFunction.FSR, GameSettingsDefine_1.EFunction.METALFX, GameSettingsDefine_1.EFunction.BLOOM, GameSettingsDefine_1.EFunction.NPCDENSITY, GameSettingsDefine_1.EFunction.VegetationDensity, GameSettingsDefine_1.EFunction.NVIDIADLSS, GameSettingsDefine_1.EFunction.NVIDIADLSSQUALITY, GameSettingsDefine_1.EFunction.XESS2, GameSettingsDefine_1.EFunction.XESS2_QUALITY, GameSettingsDefine_1.EFunction.FSR3, GameSettingsDefine_1.EFunction.FSR3_QUALITY, GameSettingsDefine_1.EFunction.RayTracing, GameSettingsDefine_1.EFunction.RayTracedReflection, GameSettingsDefine_1.EFunction.RayTracedGI, GameSettingsDefine_1.EFunction.RayTracedShadow, GameSettingsDefine_1.EFunction.LOADINGRANGESCALELEVEL]);
exports.makeImageQualityCustomSet = new Set([GameSettingsDefine_1.EFunction.HIGHESTFPS, GameSettingsDefine_1.EFunction.SHADOWQUALITY, GameSettingsDefine_1.EFunction.NIAGARAQUALITY, GameSettingsDefine_1.EFunction.IMAGEDETAIL, GameSettingsDefine_1.EFunction.ANTIALISING, GameSettingsDefine_1.EFunction.SCENEAO, GameSettingsDefine_1.EFunction.VOLUMEFOG, GameSettingsDefine_1.EFunction.VOLUMELIGHT, GameSettingsDefine_1.EFunction.MOTIONBLUR, GameSettingsDefine_1.EFunction.PCVSYNC, GameSettingsDefine_1.EFunction.MOBILERESOLUTION, GameSettingsDefine_1.EFunction.NPCDENSITY, GameSettingsDefine_1.EFunction.VegetationDensity, GameSettingsDefine_1.EFunction.BLOOM, GameSettingsDefine_1.EFunction.FSR, GameSettingsDefine_1.EFunction.NVIDIADLSS, GameSettingsDefine_1.EFunction.NVIDIADLSSQUALITY, GameSettingsDefine_1.EFunction.XESS2, GameSettingsDefine_1.EFunction.XESS2_QUALITY, GameSettingsDefine_1.EFunction.FSR3, GameSettingsDefine_1.EFunction.FSR3_QUALITY, GameSettingsDefine_1.EFunction.LOADINGRANGESCALELEVEL]);
exports.filterSettingParams = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
exports.DEFAULT_FILTER_SETTING_INTENSITY_VALUE = 1;
exports.DEFAULT_FILTER_SETTING_VALUE = 0.5;
exports.DEFAULT_FILTER_SENIOR_SETTING_VALUE = 0;
exports.SEETING_LOAD_FLUID = "Text_SettingLoadFluid_text";
exports.SEETING_LOAD_LAGGY = "Text_SettingLoadLaggy_text";
exports.SEETING_LOAD_OVER = "Text_SettingLoadOver_text";
exports.SEETING_LOAD_FLUID_COLOR = "/Game/Aki/UI/UIResources/UiSet/Atlas/SP_BarGreen.SP_BarGreen";
exports.SEETING_LOAD_LAGGY_COLOR = "/Game/Aki/UI/UIResources/UiSet/Atlas/SP_BarOrange.SP_BarOrange";
exports.SEETING_LOAD_OVER_COLOR = "/Game/Aki/UI/UIResources/UiSet/Atlas/SP_BarRed.SP_BarRed";
exports.qualityLevelScores = [120, 135, 143, 150];
exports.pcQualityLevelScores = [0, 25, 50, 70, 85, 100];
exports.pcQualityLevelWeights = [1.35, 1.15, 1, 0.8, 0.65, 0.45];
exports.mobileResolutionScores = [0.49, 0.64, 0.7225, 1];
exports.shadowQualityScores = [0, 6, 10, 12];
exports.niagaraQualityScores = [0, 4, 6];
exports.imageDetailScores = [0, 6, 12, 20];
exports.sceneAoScores = [0, 6, 8, 10];
exports.antiAliasingScores = [0, 10];
exports.volumeFogScores = [0, 3, 6, 10];
exports.volumeLightScores = [0, 2];
exports.motionBlurScores = [0, 6];
exports.amdFsrScores = [0, 10];
exports.metalFxScores = [0, 3];
exports.bloomScores = [0, 3];
exports.npcDensityScores = [0, 3, 6];
exports.vegetationDensityScores = [0, 3, 6, 10];
exports.superResolutionScores = [-70, -55, -45, -35, -10, -7, -3, 0];
exports.rayTracingGIScores = [0, 8, 15, 15];
exports.rayTracingReflectionScores = [0, 7, 15, 25];
exports.rayTracedShadowScores = [0, 5, 5, 10];
exports.pcLoadingRangeScores = [0, 80, 160];
exports.mobileLoadingRangeScores = [0, 80, 160];
exports.STOP_GUIDE_TAG = "MenuView";
exports.CUSTOM_TEXT_ID = "MenuConfig_5_OptionsName_4";
exports.TARGET_HIT_ITEM_FOR_FILTER = "TexFilter";
exports.TARGET_HIT_ITEM_FOR_LEFT_ARROW = "TexArrowL";
exports.TARGET_HIT_ITEM_FOR_RIGHT_ARROW = "TexArrowR";
exports.FILTER_SETTING_HELP_ID = 323;
exports.FILTER_SETTING_TITLE_TEXT_ID = "PrefabTextItem_3846974633_Text";
exports.EYE_PROTECT_SETTING_HELP_ID = 390;
exports.FILTER_SETTING_TITLE_ICON_RESOURCE_ID = "TexFilterIcon";
exports.FILTER_SETTING_COORDINATE_TEXT_ID = "PrefabTextItem_2070808429_Text";
exports.FILTER_SETTING_FILTER_TEXTURE_COUNT = 5;
exports.FILTER_SETTING_DEFAULT_FILTER_ID = 1;
exports.DETAIL_SPRITE_PATH = "/Game/Aki/UI/UIResources/Common/Atlas/SP_BtnQuest.SP_BtnQuest";
exports.LOCK_SPRITE_PATH = "/Game/Aki/UI/UIResources/Common/Atlas/SP_CommonBtnIcon5.SP_CommonBtnIcon5";
exports.DETAIL_SPRITE_VISIBLE_COLOR_SRGB = "FFF7B6FF";
exports.disableSettingsInstMap = new Map();
exports.disableSettingsWorldInstMap = new Map([[2, [GameSettingsDefine_1.EFunction.MobileButtonCustom, GameSettingsDefine_1.EFunction.MotorMobileButtonCustom]]]); //# sourceMappingURL=MenuDefine.js.map