"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.getUiModelCreateDataPreDefine = undefined;
const UiModelActorComponent_1 = require("../UiModelComponent/Common/UiModelActorComponent");
const UiModelAnimationComponent_1 = require("../UiModelComponent/Common/UiModelAnimationComponent");
const UiModelAnsControllerComponent_1 = require("../UiModelComponent/Common/UiModelAns/UiModelAnsControllerComponent");
const UiModelDataComponent_1 = require("../UiModelComponent/Common/UiModelDataComponent");
const UiModelEffectComponent_1 = require("../UiModelComponent/Common/UiModelEffectComponent");
const UiModelFadeComponent_1 = require("../UiModelComponent/Common/UiModelFadeComponent");
const UiModelLoadComponent_1 = require("../UiModelComponent/Common/UiModelLoadComponent");
const UiModelLoadingIconComponent_1 = require("../UiModelComponent/Common/UiModelLoadingIconComponent");
const UiModelRenderingMaterialComponent_1 = require("../UiModelComponent/Common/UiModelRenderingMaterialComponent");
const UiModelRotateComponent_1 = require("../UiModelComponent/Common/UiModelRotateComponent");
const UiModelTagComponent_1 = require("../UiModelComponent/Common/UiModelTagComponent");
const UiAbyssDangoLoadComponent_1 = require("../UiModelComponent/Dango/Abyss/UiAbyssDangoLoadComponent");
const UiDangoCollisionComponent_1 = require("../UiModelComponent/Dango/UiDangoCollisionComponent");
const UiDangoDataComponent_1 = require("../UiModelComponent/Dango/UiDangoDataComponent");
const UiDangoLoadComponent_1 = require("../UiModelComponent/Dango/UiDangoLoadComponent");
const UiDangoMaterialChangeComponent_1 = require("../UiModelComponent/Dango/UiDangoMaterialChangeComponent");
const UiDangoOddsComponent_1 = require("../UiModelComponent/Dango/UiDangoOddsComponent");
const UiDangoStateMachineComponent_1 = require("../UiModelComponent/Dango/UiDangoStateMachineComponent");
const UiHuluSkinDataComponent_1 = require("../UiModelComponent/Hulu/UiHuluSkinDataComponent");
const UiRoleBuffComponent_1 = require("../UiModelComponent/Role/UiRoleBuffComponent");
const UiRoleDataComponent_1 = require("../UiModelComponent/Role/UiRoleDataComponent");
const UiRoleEyeHighLightComponent_1 = require("../UiModelComponent/Role/UiRoleEyeHighLightComponent");
const UiRoleHuluComponent_1 = require("../UiModelComponent/Role/UiRoleHuluComponent");
const UiRoleHuluLightSequenceComponent_1 = require("../UiModelComponent/Role/UiRoleHuluLightSequenceComponent");
const UiRoleLoadComponent_1 = require("../UiModelComponent/Role/UiRoleLoadComponent");
const UiRoleMorphComponent_1 = require("../UiModelComponent/Role/UiRoleMorphComponent");
const UiRoleStateMachineComponent_1 = require("../UiModelComponent/Role/UiRoleStateMachineComponent");
const UiRoleWeaponComponent_1 = require("../UiModelComponent/Role/UiRoleWeaponComponent");
const UiWeaponBreachDaComponent_1 = require("../UiModelComponent/Weapon/UiWeaponBreachDaComponent");
const UiWeaponDataComponent_1 = require("../UiModelComponent/Weapon/UiWeaponDataComponent");
const UiModelCreateData_1 = require("../UiModelCreateData/UiModelCreateData");
let uiModelCreateDataPreDefine = undefined;
const getUiModelCreateDataPreDefine = () => uiModelCreateDataPreDefine = uiModelCreateDataPreDefine || {
  [0]: new UiModelCreateData_1.UiModelCreateData(0, 0, 0, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent, UiRoleDataComponent_1.UiRoleDataComponent, UiRoleHuluComponent_1.UiRoleHuluComponent, UiRoleLoadComponent_1.UiRoleLoadComponent, UiRoleStateMachineComponent_1.UiRoleStateMachineComponent]),
  1: new UiModelCreateData_1.UiModelCreateData(0, 0, 1, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelLoadingIconComponent_1.UiModelLoadingIconComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent, UiModelFadeComponent_1.UiModelFadeComponent, UiModelTagComponent_1.UiModelTagComponent, UiRoleDataComponent_1.UiRoleDataComponent, UiRoleLoadComponent_1.UiRoleLoadComponent, UiRoleStateMachineComponent_1.UiRoleStateMachineComponent, UiRoleWeaponComponent_1.UiRoleWeaponComponent, UiRoleHuluComponent_1.UiRoleHuluComponent, UiRoleEyeHighLightComponent_1.UiRoleEyeHighLightComponent, UiRoleHuluLightSequenceComponent_1.UiRoleHuluLightSequenceComponent, UiRoleBuffComponent_1.UiRoleBuffComponent, UiRoleMorphComponent_1.UiRoleMorphComponent]),
  2: new UiModelCreateData_1.UiModelCreateData(1, 1, 2, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelLoadComponent_1.UiModelLoadComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent, UiWeaponDataComponent_1.UiWeaponDataComponent, UiWeaponBreachDaComponent_1.UiWeaponBreachDaComponent]),
  3: new UiModelCreateData_1.UiModelCreateData(1, 1, 3, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelLoadComponent_1.UiModelLoadComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent, UiModelRotateComponent_1.UiModelRotateComponent, UiWeaponDataComponent_1.UiWeaponDataComponent, UiWeaponBreachDaComponent_1.UiWeaponBreachDaComponent]),
  4: new UiModelCreateData_1.UiModelCreateData(1, 1, 4, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelLoadComponent_1.UiModelLoadComponent, UiModelLoadingIconComponent_1.UiModelLoadingIconComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent, UiModelRotateComponent_1.UiModelRotateComponent, UiWeaponDataComponent_1.UiWeaponDataComponent, UiWeaponBreachDaComponent_1.UiWeaponBreachDaComponent]),
  5: new UiModelCreateData_1.UiModelCreateData(3, 1, 5, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelLoadComponent_1.UiModelLoadComponent, UiModelRotateComponent_1.UiModelRotateComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiHuluSkinDataComponent_1.UiHuluSkinDataComponent]),
  6: new UiModelCreateData_1.UiModelCreateData(3, 1, 6, [UiModelDataComponent_1.UiModelDataComponent, UiModelLoadingIconComponent_1.UiModelLoadingIconComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelLoadComponent_1.UiModelLoadComponent, UiModelRotateComponent_1.UiModelRotateComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiHuluSkinDataComponent_1.UiHuluSkinDataComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent]),
  7: new UiModelCreateData_1.UiModelCreateData(2, 1, 7, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent]),
  8: new UiModelCreateData_1.UiModelCreateData(2, 1, 8, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelLoadComponent_1.UiModelLoadComponent, UiModelLoadingIconComponent_1.UiModelLoadingIconComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelAnimationComponent_1.UiModelAnimationComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent]),
  9: new UiModelCreateData_1.UiModelCreateData(0, 0, 9, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent, UiRoleDataComponent_1.UiRoleDataComponent, UiRoleLoadComponent_1.UiRoleLoadComponent, UiModelLoadingIconComponent_1.UiModelLoadingIconComponent, UiRoleStateMachineComponent_1.UiRoleStateMachineComponent]),
  10: new UiModelCreateData_1.UiModelCreateData(0, 0, 10, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelAnimationComponent_1.UiModelAnimationComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent, UiRoleLoadComponent_1.UiRoleLoadComponent, UiRoleDataComponent_1.UiRoleDataComponent]),
  11: new UiModelCreateData_1.UiModelCreateData(1, 1, 11, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelLoadComponent_1.UiModelLoadComponent, UiModelAnimationComponent_1.UiModelAnimationComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent, UiModelRotateComponent_1.UiModelRotateComponent]),
  12: new UiModelCreateData_1.UiModelCreateData(0, 0, 12, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelLoadComponent_1.UiModelLoadComponent, UiModelAnimationComponent_1.UiModelAnimationComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent, UiModelRotateComponent_1.UiModelRotateComponent, UiRoleWeaponComponent_1.UiRoleWeaponComponent, UiRoleDataComponent_1.UiRoleDataComponent, UiRoleStateMachineComponent_1.UiRoleStateMachineComponent, UiRoleLoadComponent_1.UiRoleLoadComponent, UiModelFadeComponent_1.UiModelFadeComponent]),
  13: new UiModelCreateData_1.UiModelCreateData(2, 1, 8, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelLoadComponent_1.UiModelLoadComponent, UiModelLoadingIconComponent_1.UiModelLoadingIconComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelAnimationComponent_1.UiModelAnimationComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent]),
  14: new UiModelCreateData_1.UiModelCreateData(4, 2, 14, [UiModelDataComponent_1.UiModelDataComponent, UiDangoDataComponent_1.UiDangoDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiDangoLoadComponent_1.UiDangoLoadComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelFadeComponent_1.UiModelFadeComponent, UiDangoStateMachineComponent_1.UiDangoStateMachineComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent]),
  15: new UiModelCreateData_1.UiModelCreateData(4, 2, 15, [UiModelDataComponent_1.UiModelDataComponent, UiDangoDataComponent_1.UiDangoDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiDangoLoadComponent_1.UiDangoLoadComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelFadeComponent_1.UiModelFadeComponent, UiDangoStateMachineComponent_1.UiDangoStateMachineComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent, UiDangoOddsComponent_1.UiDangoOddsComponent, UiDangoCollisionComponent_1.UiDangoCollisionComponent, UiDangoMaterialChangeComponent_1.UiDangoMaterialChangeComponent]),
  16: new UiModelCreateData_1.UiModelCreateData(4, 2, 16, [UiModelDataComponent_1.UiModelDataComponent, UiDangoDataComponent_1.UiDangoDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiAbyssDangoLoadComponent_1.UiAbyssDangoLoadComponent, UiModelLoadingIconComponent_1.UiModelLoadingIconComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelAnimationComponent_1.UiModelAnimationComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent]),
  17: new UiModelCreateData_1.UiModelCreateData(5, 1, 17, [UiModelDataComponent_1.UiModelDataComponent, UiModelActorComponent_1.UiModelActorComponent, UiModelLoadComponent_1.UiModelLoadComponent, UiModelLoadingIconComponent_1.UiModelLoadingIconComponent, UiModelEffectComponent_1.UiModelEffectComponent, UiModelRenderingMaterialComponent_1.UiModelRenderingMaterialComponent, UiModelAnimationComponent_1.UiModelAnimationComponent, UiModelAnsControllerComponent_1.UiModelAnsControllerComponent])
};
exports.getUiModelCreateDataPreDefine = getUiModelCreateDataPreDefine;
//# sourceMappingURL=UiModelDefine.js.map