"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.FURNITURE_SLOT_CAMERA_FADE_IN_EXP = exports.FURNITURE_AREA_CAMERA_FADE_IN_EXP = exports.FURNITURE_SLOT_CAMERA_FADE_IN_TIME = exports.FURNITURE_AREA_CAMERA_FADE_IN_TIME = exports.FURNITURE_SLOT_CAMERA_FOV = exports.FURNITURE_AREA_CAMERA_FOV = exports.FURNITURE_SCENE_SLOT_SUB_SLOT_INDEX = exports.FURNITURE_ATMOSPHERE_TWEEN_DURATION = exports.FURNITURE_SHOP_ITEM_RED_DOT_LOCAL_KEY3 = exports.FURNITURE_DESIGN_ITEM_RED_DOT_LOCAL_KEY3 = exports.FURNITURE_HANDBOOK_ITEM_RED_DOT_LOCAL_KEY3 = exports.FURNITURE_AREA_RED_DOT_LOCAL_KEY3 = undefined;
exports.FURNITURE_AREA_RED_DOT_LOCAL_KEY3 = 1;
exports.FURNITURE_HANDBOOK_ITEM_RED_DOT_LOCAL_KEY3 = 2;
exports.FURNITURE_DESIGN_ITEM_RED_DOT_LOCAL_KEY3 = 3;
exports.FURNITURE_SHOP_ITEM_RED_DOT_LOCAL_KEY3 = 4;
exports.FURNITURE_ATMOSPHERE_TWEEN_DURATION = 0.35;
exports.FURNITURE_SCENE_SLOT_SUB_SLOT_INDEX = -1;
exports.FURNITURE_AREA_CAMERA_FOV = 90;
exports.FURNITURE_SLOT_CAMERA_FOV = 75;
exports.FURNITURE_AREA_CAMERA_FADE_IN_TIME = 0;
exports.FURNITURE_SLOT_CAMERA_FADE_IN_TIME = 0.5;
exports.FURNITURE_AREA_CAMERA_FADE_IN_EXP = 1;
exports.FURNITURE_SLOT_CAMERA_FADE_IN_EXP = 16; //# sourceMappingURL=FurnitureDefine.js.map