"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.LOAD_FINISHED_PROGRESS = exports.WORLD_DONE_END_PROGRESS = exports.CREATE_ENTITY_END_PROGRESS = exports.CHECK_STREAMING_END_PROGRESS = exports.CHECK_VOXEL_STREAMING_END_PROGRESS = exports.SETDATALAYER_AND_LOADSUBLEVEL_END_PROGRESS = exports.PRELOAD_END_PROGRESS = exports.OPENLEVEL_END_PROGRESS = exports.OPENLOADING_END_PROGRESS = exports.BASE_SPEED = exports.LOADED_SPEED_RATE = undefined;
exports.LOADED_SPEED_RATE = 2;
exports.BASE_SPEED = 25;
exports.OPENLOADING_END_PROGRESS = 10;
exports.OPENLEVEL_END_PROGRESS = 30;
exports.PRELOAD_END_PROGRESS = 35;
exports.SETDATALAYER_AND_LOADSUBLEVEL_END_PROGRESS = 40;
exports.CHECK_VOXEL_STREAMING_END_PROGRESS = 50;
exports.CHECK_STREAMING_END_PROGRESS = 75;
exports.CREATE_ENTITY_END_PROGRESS = 80;
exports.WORLD_DONE_END_PROGRESS = 90;
exports.LOAD_FINISHED_PROGRESS = 100; //# sourceMappingURL=ELoadingPhase.js.map